#!/usr/bin/env python3

"""
# Adapted from https://www.codingwiththomas.com/blog/my-sphinx-best-practice-for-a-multiversion-documentation-in-different-languages
# (last visited 2025-05-20)
"""

import sys
import os
import shutil
import subprocess
from doc_builder.build_docs import main as build_docs

# Where the docs should be moved after being built
PUBLISH_DIR = "_publish"

# Where the docs should be built before being moved to PUBLISH_DIR
BUILD_DIR = "_build"

# URL or absolute file path that should contain the top-level index.html
# TODO: Make this a required cmd-line argument
SITE_ROOT = os.path.abspath(PUBLISH_DIR)

# Change to the parent director of doc-builder and add to Python path
os.chdir(os.path.join(os.path.dirname(__file__), os.pardir))
sys.path.insert(0, os.getcwd())

# Import our version definitions
print(os.getcwd())
from version_list import LATEST_REF, VERSION_LIST  # pylint: disable=wrong-import-position,import-error


# Path to certain important files
# TODO: Make these cmd-line options
CONF_PY = os.path.join("source", "conf.py")
VERSIONS_PY = os.path.join("source", "version_list.py")


def get_git_head_or_branch():
    """
    Get the name of the current branch. If detached HEAD, get current commit SHA.
    """
    try:
        result = subprocess.run(
            ["git", "symbolic-ref", "--short", "-q", "HEAD"],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            check=True,
        )
        output = result.stdout.strip()
    except subprocess.CalledProcessError:
        output = ""

    if not output:
        # Fallback to commit SHA
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            check=True,
        )
        output = result.stdout.strip()

    return output


def checkout_and_build(version):
    """
    Check out docs for a version and build
    """

    # Check that conf.py exists
    if not os.path.exists(CONF_PY):
        raise FileNotFoundError(CONF_PY)

    # Get the current branch, or SHA if detached HEAD
    orig_ref = get_git_head_or_branch()

    # Check out the ref for this version, skipping some files
    things_to_skip = [CONF_PY, VERSIONS_PY, "doc-builder"]
    for thing in things_to_skip:
        # Error if it contains uncommitted changes
        cmd = f"git add . && git diff --quiet {thing} && git diff --cached --quiet {thing}"
        try:
            subprocess.check_output(cmd, shell=True)
        except subprocess.CalledProcessError as e:
            subprocess.check_output(
                "git reset", shell=True
            )  # Unstage files staged by `git add`
            msg = f"Important file/submodule may contain uncommitted changes: '{thing}'"
            raise RuntimeError(msg) from e

        # Stage it so it won't be modified during checkout
        # subprocess.check_output("git add " + thing, shell=True)

    subprocess.check_output("git checkout " + version.ref, shell=True)
    for thing in things_to_skip:
        subprocess.check_output(f"git checkout {LATEST_REF} -- {thing}", shell=True)

    # Build the docs for this version
    build_args = [
        "-r",
        BUILD_DIR,
        "-v",
        version.short_name,
        "--version-display-name",
        version.display_name,
        "--versions",
        "--site-root",
        os.path.abspath(SITE_ROOT),
        # TODO: add -c for clean build
    ]
    print(" ".join(build_args))
    build_docs(build_args)

    # Go back to original place
    subprocess.check_output("git checkout " + orig_ref, shell=True)


def move_dir(src, dst):
    """
    Move the built docs to publish directory
    """
    if not os.path.exists(dst):
        os.makedirs(dst)
    subprocess.check_output("mv " + src + "* " + dst, shell=True)


def check_version_list():
    """
    Check version list for problems
    """
    has_default = False
    for version in VERSION_LIST:
        # Expect at most one version with landing_version True
        if version.landing_version:
            if has_default:
                raise RuntimeError(
                    "Expected at most one version with landing_version True"
                )
            has_default = True


def main():

    # Check version list for problems
    check_version_list()

    # and looping over all values to call our build with version, language and its tag
    for version in VERSION_LIST:
        checkout_and_build(version)
        src = os.path.join(BUILD_DIR, "versions", version.short_name, "html")
        dst = os.path.join(PUBLISH_DIR, version.subdir())
        shutil.move(src, dst)


if __name__ == "__main__":
    main()
