#!/usr/bin/env python3

"""
# Adapted from https://www.codingwiththomas.com/blog/my-sphinx-best-practice-for-a-multiversion-documentation-in-different-languages
# (last visited 2025-05-20)
"""

import os
import shutil
import subprocess
from doc_builder.build_docs import main as build_docs


class VersionInfo:
    """
    A class defining characteristics of a documentation version
    """

    # pylint: disable=too-few-public-methods
    def __init__(
        self,
        *,
        short_name,
        display_name,
        ref,
        release,
        version,
        version_label,
        landing_version=False,
    ):

        # The name of this version in file/URL paths
        self.short_name = short_name

        # What gets shown in the dropdown menu
        self.display_name = display_name

        # Whether this version should be the one on the landing page (i.e., default version)
        self.landing_version = landing_version

        # Branch, tag, or commit SHA
        self.ref = ref

        # Text for standard Sphinx substitution variable "release"
        self.release = release

        # Text for standard Sphinx substitution variable "version"
        self.version = version

        # Text for custom CTSM substitution variable "version_label"
        self.version_label = version_label

    def subdir(self):
        """
        Get the subdirectory under PUBLISH_DIR where this version's HTML will be moved
        """
        if self.landing_version:
            return ""
        return self.short_name


# Define the versions we want to build.
# short_name=None means that will be the landing version.
LATEST_REF = "auto-version-publishing"
VERSION_LIST = [
    VersionInfo(
        short_name="latest",
        display_name="Latest development code",
        landing_version=True,
        ref=LATEST_REF,
        release="CTSM master",
        version="CTSM1",
        version_label="the latest development code",
    ),
    VersionInfo(
        short_name="release-clm5.0",
        display_name="CLM5.0",
        ref="release-clm5.0",
        release="release-clm5.0",
        version="CLM5.0",
        version_label="CLM5.0 (CESM2.1)",
    ),
]

# Where the docs should be moved after being built
PUBLISH_DIR = "_publish"

# Where the docs should be built before being moved to PUBLISH_DIR
BUILD_DIR = "_build"

# URL or absolute file path that should contain the top-level index.html
# TODO: Make this a required cmd-line argument
SITE_ROOT = os.path.abspath(PUBLISH_DIR)

# Change to the parent director of doc-builder
os.chdir(os.path.join(os.path.dirname(__file__), os.pardir))

# Path to conf.py
# TODO: Make this a cmd-line option
CONF_PY = os.path.join("source", "conf.py")


def get_git_head_or_branch():
    try:
        result = subprocess.run(
            ["git", "symbolic-ref", "--short", "-q", "HEAD"],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            check=True,
        )
        output = result.stdout.strip()
    except subprocess.CalledProcessError:
        output = ""

    if not output:
        # Fallback to commit SHA
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            check=True,
        )
        output = result.stdout.strip()

    return output


def checkout_and_build(version):
    """
    Check out docs for a version and build
    """

    # Check that conf.py exists
    if not os.path.exists(CONF_PY):
        raise FileNotFoundError(CONF_PY)

    # Get the current branch, or SHA if detached HEAD
    orig_ref = get_git_head_or_branch()

    # Check out the ref for this version, skipping some files
    things_to_skip = [CONF_PY, "doc-builder"]
    for thing in things_to_skip:
        # Error if it contains uncommitted changes
        cmd = f"git add . && git diff --quiet {thing} && git diff --cached --quiet {thing}"
        try:
            subprocess.check_output(cmd, shell=True)
        except subprocess.CalledProcessError as e:
            subprocess.check_output(
                "git reset", shell=True
            )  # Unstage files staged by `git add`
            msg = f"Important file/submodule may contain uncommitted changes: '{thing}'"
            raise RuntimeError(msg) from e

        # Stage it so it won't be modified during checkout
        # subprocess.check_output("git add " + thing, shell=True)

    subprocess.check_output("git checkout " + version.ref, shell=True)
    for thing in things_to_skip:
        subprocess.check_output(f"git checkout {LATEST_REF} -- {thing}", shell=True)

    # Build the docs for this version
    build_args = [
        "-r",
        BUILD_DIR,
        "-v",
        version.short_name,
        "--version-display-name",
        version.display_name,
        "--versions",
        "--site-root",
        os.path.abspath(SITE_ROOT),
        # TODO: add -c for clean build
    ]
    print(" ".join(build_args))
    # build_docs(build_args)

    if version.short_name != "latest":
        winriewnr

    # Go back to original place
    subprocess.check_output("git checkout " + orig_ref, shell=True)


def move_dir(src, dst):
    """
    Move the built docs to publish directory
    """
    if not os.path.exists(dst):
        os.makedirs(dst)
    subprocess.check_output("mv " + src + "* " + dst, shell=True)


def check_version_list():
    """
    Check version list for problems
    """
    has_default = False
    for version in VERSION_LIST:
        # Expect at most one version with landing_version True
        if version.landing_version:
            if has_default:
                raise RuntimeError(
                    "Expected at most one version with landing_version True"
                )
            has_default = True


def main():

    # Check version list for problems
    check_version_list()

    # and looping over all values to call our build with version, language and its tag
    for version in VERSION_LIST:
        checkout_and_build(version)
        src = os.path.join(BUILD_DIR, "versions", version.short_name, "html")
        dst = os.path.join(PUBLISH_DIR, version.subdir())
        shutil.move(src, dst)


if __name__ == "__main__":
    main()
