#!/usr/bin/env python3

"""
# Adapted from https://www.codingwiththomas.com/blog/my-sphinx-best-practice-for-a-multiversion-documentation-in-different-languages
# (last visited 2025-05-20)
"""

import os
import shutil
import subprocess
from doc_builder.build_docs import main as build_docs

class VersionInfo:
    """
    A class defining characteristics of a documentation version
    """

    # pylint: disable=too-few-public-methods
    def __init__(self, *, short_name, display_name, ref):

        # The name of this version in file/URL paths
        self.short_name = short_name

        # What gets shown in the dropdown menu
        self.display_name = display_name

        # Branch, tag, or commit SHA
        self.ref = ref


# Define the versions we want to build.
# short_name=None means that will be the landing version.
LATEST_REF = "auto-version-publishing"
VERSION_LIST = [
    VersionInfo(
        short_name="latest", display_name="Latest development code", ref=LATEST_REF
    ),
    VersionInfo(
        short_name="release-clm5.0", display_name="CLM5.0", ref="release-clm5.0"
    ),
]

# Where the docs should be moved after being built
PUBLISH_DIR = "_publish"

# Where the docs should be built before being moved to PUBLISH_DIR
BUILD_DIR = "_build"

# URL or absolute file path that should contain the top-level index.html
# TODO: Make this a required cmd-line argument
SITE_ROOT = os.path.abspath(PUBLISH_DIR)

# Change to the parent director of doc-builder
os.chdir(os.path.join(os.path.dirname(__file__), os.pardir))

# Path to conf.py
# TODO: Make this a cmd-line option
CONF_PY = os.path.join("source", "conf.py")

def get_git_head_or_branch():
    try:
        result = subprocess.run(
            ['git', 'symbolic-ref', '--short', '-q', 'HEAD'],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            check=True
        )
        output = result.stdout.strip()
    except subprocess.CalledProcessError:
        output = ''

    if not output:
        # Fallback to commit SHA
        result = subprocess.run(
            ['git', 'rev-parse', 'HEAD'],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            check=True
        )
        output = result.stdout.strip()

    return output

def checkout_and_build(version):
    """
    Check out docs for a version and build
    """

    # Check that conf.py exists
    if not os.path.exists(CONF_PY):
        raise FileNotFoundError(CONF_PY)

    # Get the current branch, or SHA if detached HEAD
    orig_ref = get_git_head_or_branch()

    # Check out the ref for this version, skipping some files
    things_to_skip = [CONF_PY, "doc-builder"]
    for thing in things_to_skip:
        subprocess.check_output("git add " + thing, shell=True)
    subprocess.check_output("git checkout " + version.ref, shell=True)
    subprocess.check_output(f"git checkout {LATEST_REF} -- {CONF_PY}", shell=True)

    # Build the docs for this version
    build_args = [
        "-r", BUILD_DIR,
        "-v", version.short_name,
        "--version-display-name", version.display_name,
        "--versions",
        "--site-root", os.path.abspath(SITE_ROOT),
        # TODO: add -c for clean build
    ]
    print(" ".join(build_args))
    build_docs(build_args)
    
    # Go back to original place
    subprocess.check_output("git checkout " + orig_ref, shell=True)


def move_dir(src, dst):
    """
    Move the built docs to publish directory
    """
    if not os.path.exists(dst):
        os.makedirs(dst)
    subprocess.check_output("mv " + src + "* " + dst, shell=True)


def check_version_list():
    """
    Check version list for problems
    """
    # n_none = 0
    # for version in VERSION_LIST:
    #     # Expect exactly one version with short_name=None
    #     n_none += int(version.short_name is None)
    # if n_none != 1:
    #     raise RuntimeError(f"Expected one version with short_name=None; found {n_none}")


def main():

    # Check version list for problems
    check_version_list()

    # and looping over all values to call our build with version, language and its tag
    for version in VERSION_LIST:
        checkout_and_build(version)
        src = os.path.join(BUILD_DIR, "versions", version.short_name, "html")
        # TODO: If default version, don't append version.short_name
        dst = os.path.join(PUBLISH_DIR, version.short_name)
        shutil.move(src, dst)


if __name__ == "__main__":
    main()
